---
- name: Add hyperhdr apt gpg key
  become: true
  ansible.builtin.apt_key:
    url: "{{ hyperhdr_apt_key_url }}/hyperhdr.public.apt.gpg.key"
    keyring: "{{ hyperhdr_keyring }}"
    state: present

# - name: Add hyperhdr apt gpg key
#   become: true
#   ansible.builtin.get_url:
#     url: "{{ hyperhdr_apt_key_url }}/hyperhdr.public.apt.gpg.key"
#     dest: /etc/apt/trusted.gpg.d/hyperhdr.asc
#     mode: '0644'
#     force: true

- name: Add hyperhdr repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by={{ hyperhdr_keyring }}]
        {{ hyperhdr_apt_key_url }}/ {{ ansible_distribution_release | lower }} main
    state: present

- name: Update apt packages with new apt repository
  become: true
  ansible.builtin.apt:
    update_cache: true

# - name: Script from hyperhdr website
#   command: |
#     type -p curl >/dev/null || sudo apt install curl -y
#     curl -fsSL https://awawa-dev.github.io/hyperhdr.public.apt.gpg.key | sudo dd of=/usr/share/keyrings/hyperhdr.public.apt.gpg.key \
#     && sudo chmod go+r /usr/share/keyrings/hyperhdr.public.apt.gpg.key \
#     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hyperhdr.public.apt.gpg.key] https://awawa-dev.github.io $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hyperhdr.list > /dev/null \
#     && sudo apt update \
#     && sudo apt install hyperhdr -y
