---
# tasks file for hyperhdr
- name: Include role tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - prerequisites.yml
    - apt.yml
    - install.yml
    - service.yml
    - verify.yml
    # - gtp.yml

- name: Include verify tasks
  ansible.builtin.include_tasks: verify.yml
  when: disable_verification is false
